---
- hosts: localhost
  become: true
  roles:
    - { role: core, tags: ['core'] }
    - { role: osmium, tags: ['osmium'] }
    - { role: radium, tags: ['radium'] }
    - { role: workstation, tags: ['workstation'] }
