---
- name: Enable additional repositories
  include_tasks: repo.yml

- name: Install base packages
  include_tasks: packages.yml
  tags: packages

- name: Configure networking
  include_tasks: networking.yml
  tags: 
    - networking
    - wifi

- name: Setup samba credentials
  include_tasks: samba.yml
  tags: samba
