- name: Copy dhcpcd config
  ansible.builtin.copy:
    src: ../files/dhcpcd.conf
    dest: /etc/dhcpcd.conf
  tags: networking

- name: Copy resolv config
  ansible.builtin.copy:
    src: ../files/resolv.conf
    dest: /etc/resolv.conf
  tags: networking

- name: Enable & start dhcpcd
  ansible.builtin.systemd:
    name: dhcpcd.service
    enabled: yes
    state: started
  tags: networking

- name: Enable & start systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved.service
    enabled: yes
    state: started
  tags: networking

- name: Copy hosts file
  ansible.builtin.copy:
    src: ../files/hosts
    dest: /etc/hosts
  tags: networking

- name: Create iwd directory for main config
  ansible.builtin.file:
    path: /etc/iwd
    state: directory
    mode: 0700
  tags:
    - networking
    - wifi

- name: Copy iwd main.conf 
  ansible.builtin.copy:
    src: ../files/iwd/main.conf
    dest: /etc/iwd/main.conf
    owner: root
    group: root
    mode: 0600
  tags:
    - networking
    - wifi

- name: Create iwd directory for network configs
  ansible.builtin.file:
    path: /var/lib/iwd
    state: directory
    mode: 0700
  tags:
    - networking
    - wifi

- name: Copy iwd config
  ansible.builtin.copy:
    src: ../files/iwd/BCNet.8021x
    dest: /var/lib/iwd/BCNet.8021x
    decrypt: yes
    owner: root
    group: root
    mode: 0600
  tags:
    - networking
    - wifi

- name: Enable & start iwd
  ansible.builtin.systemd:
    name: iwd.service
    enabled: yes
    state: started
  tags:
    - networking
    - wifi
