---
- name: Grab variables
  ansible.builtin.include_vars:
    file: ../vars/samba.yml
  tags: samba

- name: Create samba credentials directory
  ansible.builtin.file:
    path: /etc/samba/credentials
    state: directory
    mode: 0700
  tags: samba

- name: Create samba credential for helium share
  ansible.builtin.file:
    path: /etc/samba/credentials/helium
    owner: root
    group: root
    mode: 0600
    state: touch
  tags: samba

- name: Set samba username for helium share
  ansible.builtin.lineinfile:
    path: /etc/samba/credentials/helium
    regexp: '^username='
    line: "username={{ samba_username }}"
  tags: samba

- name: Set samba password for helium share
  ansible.builtin.lineinfile:
    path: /etc/samba/credentials/helium
    regexp: '^password='
    line: "password={{ samba_password }}"
  tags: samba

- name: Create mnt directories
  ansible.builtin.file:
    path: /mnt/helium
    state: directory
    owner: brandon
    group: wheel
  tags: samba
