---
- name: Create ~/.local/bin
  ansible.builtin.file:
    path: /home/brandon/.local/bin
    state: directory
    owner: brandon
    group: wheel

- name: Copy scripts into ~/.local/bin
  ansible.builtin.copy:
    src: ../files/scripts/
    dest: /home/brandon/.local/bin
    owner: brandon
    group: wheel
    mode: 0755

- name: Copy .xinitrc
  ansible.builtin.copy:
    src: ../files/config/.xinitrc
    dest: /home/brandon/.xinitrc
    owner: brandon
    group: wheel
    mode: 0655
    backup: yes
  tags: config

- name: Copy .xprofile
  ansible.builtin.copy:
    src: ../files/config/.xprofile
    dest: /home/brandon/.xprofile
    owner: brandon
    group: wheel
    mode: 0755
    backup: yes
  tags: config

- name: Copy .vimrc
  ansible.builtin.copy:
    src: ../files/config/.vimrc
    dest: /home/brandon/.vimrc
    owner: brandon
    group: wheel
    mode: 0755
  tags: config

- name: Create colorschemes dir
  ansible.builtin.file:
    path: /home/brandon/.vim/colors
    state: directory
    owner: brandon
    group: wheel
  tags: config

- name: Copy vim colorschemes
  ansible.builtin.copy:
    src: ../files/config/colorschemes/
    dest: /home/brandon/.vim/colors/
    owner: brandon
    group: wheel
    mode: 0755
  tags: config

- name: Copy .zprofile
  ansible.builtin.copy:
    src: ../files/config/.zprofile
    dest: /home/brandon/.zprofile
    owner: brandon
    group: wheel
    mode: 0655
  tags: config

- name: Copy .zshrc
  ansible.builtin.copy:
    src: ../files/config/.zshrc
    dest: /home/brandon/.zshrc
    owner: brandon
    group: wheel
    mode: 0655
  tags: config

- name: Set zsh as shell of choice
  user:
    name: brandon
    shell: /usr/bin/zsh
  tags: config

- name: Copy newsboat urls
  ansible.builtin.copy:
    src: ../files/config/.newsboat/urls
    dest: /home/brandon/.newsboat/urls
    owner: brandon
    group: wheel
    mode: 0644
  tags: config

