- name: Install dmenu
  pacman:
    name:
      - dmenu
    state: present

- name: Clone st
  ansible.builtin.git:
    repo: https://github.com/brandonwkipp/st
    dest: /home/brandon/www/st
    version: patches
  become: true
  become_user: brandon

- name: Install st
  ansible.builtin.shell:
    chdir: /home/brandon/www/st
    cmd: make clean install

- name: Clone dwmblocks
  ansible.builtin.git:
    repo: https://github.com/brandonwkipp/dwmblocks
    dest: /home/brandon/www/dwmblocks
    version: patches
  become: true
  become_user: brandon

- name: Install dwmblocks
  ansible.builtin.shell:
    chdir: /home/brandon/www/dwmblocks
    cmd: make && make clean install

- name: Clone dwm
  ansible.builtin.git:
    repo: https://github.com/brandonwkipp/dwm
    dest: /home/brandon/www/dwm
    version: patches
  become: true
  become_user: brandon

- name: Install dwm
  ansible.builtin.shell:
    chdir: /home/brandon/www/dwm
    cmd: make clean install
