---
- name: Create brandon user
  include_tasks: user.yml

- name: Install packages & AUR packages
  include_tasks: packages.yml
  tags:
    - aur
    - packages

- name: Copy configs
  include_tasks: config.yml
  tags:
    - config

- name: Install dwm
  include_tasks: dwm.yml
  tags: dwm

#- name: Install Talon
#  include_tasks: talon.yml
#  tags:
#    - packages
#    - talon

- name: Configure AxeEdit
  include_tasks: axe-edit.yml
  tags: wine

- name: Radium-specific tweaks
  include_tasks: radium.yml
  when: machine_name == "radium"
  tags: [radium]
