---
- name: Install packages
  pacman:
    name: >
      {{ 
        audio
        + workstation
        + printer
        + vst
        + (packages_workstation_extra | default([])) 
      }}
    state: present
    update_cache: true
  tags: [packages]

- name: Install AUR packages
  kewlfft.aur.aur:
    name: "{{ aur }}"
    use: makepkg
    state: present
  become: true
  become_user: brandon
  tags: [aur]
