---
- name: Install packages
  pacman:
    name:
      - qt5-speech
    state: present
  tags:
    - packages
    - talon

- name: Fetch latest Talon
  ansible.builtin.get_url:
    url: https://talonvoice.com/dl/latest/talon-linux.tar.xz
    dest: /home/brandon/talon-linux.tar.xz
  become: true
  become_user: brandon
  tags: talon

- name: Unarchive Talon
  ansible.builtin.unarchive:
    src: /home/brandon/talon-linux.tar.xz
    dest: /home/brandon
  become: true
  become_user: brandon
  tags: talon

- name: Remove tar file
  ansible.builtin.file:
    path: /home/brandon/talon-linux.tar.xz
    state: absent
  tags: talon
