---
- name: Install uxn dependencies
  pacman:
    name:
      - portmidi
      - sdl2
    state: present
  tags: uxn

# https://lists.gnu.org/archive/html/denemo-devel/2013-09/msg00023.html
- name: Link portmidi to porttime
  ansible.builtin.file:
    src: /usr/lib/libportmidi.so
    dest: /usr/lib/libporttime.so
    state: link

- name: Clone uxn
  ansible.builtin.git:
    repo: https://git.sr.ht/~rabbits/uxn
    dest: /home/brandon/www/uxn
  become: true
  become_user: brandon
  tags: uxn

- name: Install uxn
  ansible.builtin.shell: |
    cd /home/brandon/www/uxn
    ./build.sh --no-run
    cp ./bin/uxn* /home/brandon/.local/bin/
  ignore_errors: true
  tags: uxn

- name: Clone orca
  ansible.builtin.git:
    repo: https://git.sr.ht/~rabbits/orca-toy
    dest: /home/brandon/www/orca-toy
  become: true
  become_user: brandon
  tags: uxn

- name: Install orca
  ansible.builtin.shell: |
    cd /home/brandon/www/orca-toy
    mkdir -p /home/brandon/www/orca-toy/bin
    uxnasm src/orca.tal /home/brandon/www/orca-toy/bin/orca.rom
  become: true
  become_user: brandon
  ignore_errors: true
  tags: uxn

- name: Clone shim
  ansible.builtin.git:
    repo: https://git.sr.ht/~rabbits/shim
    dest: /home/brandon/www/shim
  become: true
  become_user: brandon
  tags: uxn

- name: Install shim
  ansible.builtin.shell: |
    cd /home/brandon/www/shim
    mkdir -p /home/brandon/www/shim/bin
    ./build.sh
  become: true
  become_user: brandon
  ignore_errors: true
  tags: uxn
