- name: Install audio packages
  pacman:
    name:
      - bluez
      - bluez-utils
      - cdrtools # burning cds
      - ecasound
      # - fluidsynth # vlc midi support
      - pd
      - pipewire
      - pipewire-alsa
      - pipewire-audio
      - pipewire-jack
      - pipewire-pulse
      - qpwgraph
      - reaper
      # - soundfont-fluid # vlc midi support
      - sox
      - supercollider
      - ttf-dejavu # default font for pure data
      - vlc
      - wireplumber
      - yabridge
      - yabridgectl
    state: present
  tags: packages

- name: Install plugin packages
  pacman:
    name:
      - artyfx
      - bchoppr
      - bshapr
      - bslizr
      - calf
      - dexed
      - dragonfly-reverb
      - drumkv1
      - fabla
      - lsp-plugins
      - samplv1
      - spectmorph
      - swh-plugins
      - synthv1
      - wolf-shaper
      - x42-plugins

- name: Install audio AUR packages
  kewlfft.aur.aur:
    name:
      - a-sid
      - bitwig-studio
      - butler #auburn audio plugins
      - roomeqwizard
      # - jamulus
    use: makepkg
    state: present
  become: true
  become_user: brandon
  tags: aur
