- name: Enable Bluetooth
  ansible.builtin.systemd:
    name: bluetooth
    enabled: yes
    state: started
  tags:
    - audio
    - bluetooth

- name: Copy btconnect script
  ansible.builtin.copy:
    src: ../files/btconnect
    dest: /home/brandon/.local/bin
    owner: brandon
    group: wheel
    mode: 0755
  tags:
    - audio
    - bluetooth
