---
- name: Check if TAL Sampler is installed
  stat:
    path: ansible_env.HOME/.vst3/TAL-Sampler.vst3
  register: sampler_vst3
  tags:
    - audio
    - midi
    - plugins

- name: Install TAL Sampler if not installed
  when: not sampler_vst3.stat.exists
  block:
    - name: Download TAL Sampler
      ansible.builtin.unarchive:
        src: https://tal-software.com/downloads/plugins/TAL-Sampler_64_linux.zip
        dest: /tmp
        remote_src: yes
        list_files: yes
      register: tal_sampler_archive

    - name: Copy TAL Sampler into VST3 dir
      ansible.builtin.copy:
        src: "/tmp/{{ tal_sampler_archive.files[0].split('/')[0] }}/TAL-Sampler.vst3"
        dest: /home/brandon/.vst3
        owner: brandon
        group: wheel
        mode: "0755"
  tags:
    - audio
    - midi
    - plugins

- name: Check if TAL Vocoder is installed
  stat:
    path: ansible_env.HOME/.vst3/TAL-Vocoder.vst3
  register: vocoder_vst3
  tags:
    - audio
    - midi
    - plugins

- name: Download TAL Vocoder if not installed
  when: not vocoder_vst3.stat.exists
  block:
    - name: Download TAL Vocoder
      ansible.builtin.unarchive:
        src: https://tal-software.com/downloads/plugins/TAL-Vocoder-2_64_linux.zip
        dest: /tmp
        remote_src: yes
        list_files: yes
      register: tal_vocoder_archive

    - name: Copy TAL Vocoder into VST3 dir
      ansible.builtin.copy:
        src: "/tmp/{{ tal_vocoder_archive.files[0].split('/')[0] }}/TAL-Vocoder-2.vst3"
        dest: /home/brandon/.vst3
        owner: brandon
        group: wheel
        mode: "0755"
  tags:
    - audio
    - midi
    - plugins
