---
- name: Copy libinput for X
  ansible.builtin.copy:
    src: ../files/config/libinput
    dest: /etc/X11/xorg.conf.d/99-radium.conf
    owner: brandon
    group: wheel
    mode: 0644
  tags: config
